apiVersion: v1
kind: Secret
metadata:
  name: pach-kserve-creds
  namespace: models
  annotations:
    serving.kserve.io/s3-endpoint: pachd.pachyderm:30600
    serving.kserve.io/s3-usehttps: "0" 
type: Opaque
stringData: 
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: "" 

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: pach-deploy
  namespace: models
  annotations:
    serving.kserve.io/s3-endpoint: pachd.pachyderm:30600
    serving.kserve.io/s3-usehttps: "0" 
secrets:
- name: pach-kserve-creds

