name: Build & publish PDK images
on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfolder: ./examples/brain-mri/container/train/
            prefix: train
          - dockerfolder: ./examples/brain-mri/container/deploy/
            prefix: braindeploy

    steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - 
            name: Docker meta
            id: meta
            uses: docker/metadata-action@v5
            with:
              images: pachyderm/pdk
        -
          name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        -
          name: Build and push
          uses: docker/build-push-action@v5
          with:
            context:  ${{ matrix.dockerfolder }}
            push: true
            tags: ${{ matrix.prefix }}-${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
