name: Build & publish PDK images
on:
  push:
  pull_request:


jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfolder: ./examples/training_container/
            prefix: train
          - dockerfolder: ./examples/brain-mri/container/deploy/
            prefix: brain-deploy
          - dockerfolder: ./examples/dog-cat/container/deploy/
            prefix: dog-cat-deploy
          - dockerfolder: ./examples/object-detection/container/deploy/
            prefix: object-detection-deploy
          - dockerfolder: ./examples/sentiment-analysis/container/deploy/
            prefix: sentiment-analysis-deploy

    steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - uses: dorny/paths-filter@v2
          id: filter
          with:
            filters: |
              dockerchange:
                - '{{ matrix.dockerfolder }}/**'
        - 
            name: Docker meta
            id: meta
            if: steps.filter.outputs.dockerchange == 'true'
            uses: docker/metadata-action@v5
            with:
              images: pachyderm/pdk
              tags: |
                # branch event
                type=sha,prefix=${{ matrix.prefix }}-,event=branch
                # tag event
                type=ref,prefix=${{ matrix.prefix }}-,event=tag
              flavor: |
                
        -
          name: Login to Docker Hub
          uses: docker/login-action@v3
          if: steps.filter.outputs.dockerchange == 'true'
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        -
          name: Build and push
          uses: docker/build-push-action@v5
          if: steps.filter.outputs.dockerchange == 'true'
          with:
            context:  ${{ matrix.dockerfolder }}
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
